@API_HostAddress = http://localhost:5000/api/auth

# Create Account
POST {{API_HostAddress}}/register
Accept: application/json
Content-Type: application/json

{
  "name": "Földesi Csaba",
  "email": "cs@cs.hu",
  "avatar": ""
}
###


# Login
# @name postLogin
POST {{API_HostAddress}}
Accept: application/json
Content-Type: application/json

{
  "email": "admin@admin.hu",
  "password": "Password1"
}
###
@accessToken = {{postLogin.response.body.data.accessToken}}


#Logout
POST {{API_HostAddress}}/logout
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{accessToken}}

###

# Get profile
GET {{API_HostAddress}}
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IkNzYWJhIEbDtmxkZXNpIiwibmFtZWlkIjoiMjJhMTEwNmQtOThkMy00ZDA5LWExZWYtNTYxZjJlYTljOTJiIiwiZW1haWwiOiJjc2FidXNAZ21haWwuY29tIiwiUHJvdmlkZXIiOiJHaXRIdWIiLCJuYmYiOjE3MzU2NzY5MTMsImV4cCI6MTczNTY3NzIxMywiaWF0IjoxNzM1Njc2OTEzfQ.G7_Gh8xItwS1m1Zrd5hctGqIpMAqnhVr3f7XZbmjAHKakfl0y3jOcdxO39Q6WfSPreN3JDtmF2PLJ5uyp-As8g


###

# Refresh token
POST {{API_HostAddress}}/token/XpPjorvXO1857u7KQBQ4pYqI6Pj1U1fDHi4Py2UkXWM
Accept: application/json
Content-Type: application/json

###