@API_HostAddress = http://localhost:5000/api/auth

# Create Account
POST {{API_HostAddress}}/signup
Accept: application/json
Content-Type: application/json

{
  "name": "Földesi Csaba",
  "email": "cs1@cs.hu",
  "password": "Password+1"
}
###


# Login
# @name postLogin
POST {{API_HostAddress}}/signin
Accept: application/json
Content-Type: application/json

{
  "email": "cs@cs.cs",
  "password": "Password+1"
}
###
//@accessToken = {{postLogin.response.body.data.accessToken}}


#Logout
GET {{API_HostAddress}}/signout
Accept: application/json
Content-Type: application/json
Cookie: AccessToken=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IkNzYWJhIEbDtmxkZXNpIiwibmFtZWlkIjoiMjJhMTEwNmQtOThkMy00ZDA5LWExZWYtNTYxZjJlYTljOTJiIiwiZW1haWwiOiJjc2FidXNAZ21haWwuY29tIiwiUHJvdmlkZXIiOiJHaXRIdWIiLCJuYmYiOjE3MzYwODc2MDEsImV4cCI6MTczNjA4NzkwMSwiaWF0IjoxNzM2MDg3NjAxfQ.7TwyQ5PTZax8abyi8Em63GRsmuYN-ebqIvm59m4xbDAjuAWu4a_nwen2Qf8aXDfZFMBghbop10QkXP5LXpdkkA

###

# Get profile
GET {{API_HostAddress}}
Accept: application/json
Content-Type: application/json
Cookie: AccessToken=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IkbDtmxkZXNpIENzYWJhIiwibmFtZWlkIjoiZGMzYzIyOTItMWEzZi00ZmMwLWI4ZjYtYzRkOTNiZTM0MWI4IiwiZW1haWwiOiJjc0Bjcy5jcyIsIlByb3ZpZGVyIjoiIiwibmJmIjoxNzM2MDgxMTExLCJleHAiOjE3MzYwODE0MTEsImlhdCI6MTczNjA4MTExMX0.Q5zCTlna5EXjX0kmXnAkvvE1FCnm3lMR5Sl436eVrwcC-Qj6itU1aohVfz4rMqqTP6yx3p7z85x_J0puFjfwTA

###

# Refresh token
POST {{API_HostAddress}}/refresh-token
Accept: application/json
Content-Type: application/json
Cookie: RefreshToken=

###