@API_HostAddress = http://localhost:5000/api/auth

# Get profile
GET {{API_HostAddress}}
Accept: application/json
Cookie: AccessToken=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IkNzYWJhIEbDtmxkZXNpIiwibmFtZWlkIjoiMjJhMTEwNmQtOThkMy00ZDA5LWExZWYtNTYxZjJlYTljOTJiIiwiZW1haWwiOiJjc2FidXNAZ21haWwuY29tIiwiUHJvdmlkZXIiOiJHaXRIdWIiLCJuYmYiOjE3MzU3NDMzNjksImV4cCI6MTczNTc0MzY2OSwiaWF0IjoxNzM1NzQzMzY5fQ.QDezz8Kkg8quShO9sy6WkjRSibiiu1cpLXq0PA2wZesin_aO0PTyvNQSU5Y8bClht1QiuBwVe5jaODKhXGzIYQ

###

#Sign up
POST {{API_HostAddress}}/signup
Accept: application/json
Content-Type: application/json

{
    "name": "Földesi Csaba",
    "email": "cs@cs.cs",
    "password": "Password+1"
}
###


#Sign in
POST {{API_HostAddress}}/signin
Accept: application/json
Content-Type: application/json

{
    "email": "cs@cs.cs",
    "password": "Password+1"
}
###

# Sign out
GET {{API_HostAddress}}/signout
Accept: application/json
Content-Type: application/json
Cookie: AccessToken=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IkbDtmxkZXNpIENzYWJhIiwibmFtZWlkIjoiZGMzYzIyOTItMWEzZi00ZmMwLWI4ZjYtYzRkOTNiZTM0MWI4IiwiZW1haWwiOiJjc0Bjcy5jcyIsIlByb3ZpZGVyIjoiIiwibmJmIjoxNzM2MDg4NjcyLCJleHAiOjE3MzYwODg5NzIsImlhdCI6MTczNjA4ODY3Mn0.m0WHKZGrXr0GoG_DuxiFS8LfimQJ1qEgokbaEYpNqruogXy9npRnAfy62RnTrkMoXDKlw73oXFXhLLUXD0iC8g

###

# Test protected endpoint
GET {{API_HostAddress}}/protected
Accept: application/json
Content-Type: application/json
Authorization: Bearer 


###


# Refresh token
GET {{API_HostAddress}}/refresh-token
Accept: application/json
Content-Type: application/json
Cookie: RefreshToken=9bnPTCYM8PxxzLnzuGIyg6LHXJcg9qrB9TB7TSPjKk8
###