@API_HostAddress = http://localhost:5000/api/channel


# Get Workspaces Channels
GET {{API_HostAddress}}/list?workspaceId=0eb2a9d5-30bd-425f-a1db-091bc3597647
Accept: application/json
Cookie: AccessToken=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IkNzYWJhIEbDtmxkZXNpIiwibmFtZWlkIjoiMjJhMTEwNmQtOThkMy00ZDA5LWExZWYtNTYxZjJlYTljOTJiIiwiZW1haWwiOiJjc2FidXNAZ21haWwuY29tIiwiUHJvdmlkZXIiOiJHaXRIdWIiLCJuYmYiOjE3MzYzNDM2MjgsImV4cCI6MTczNjM0MzkyOCwiaWF0IjoxNzM2MzQzNjI4fQ.l_bG1MOuKEEI9Pfm_u0pHjLCIma8508a3vUk1OQO3-JO2ceFnyXUf_mho1lxhkONwiOGppZ6sZdbdVe3kS3zEg

###

# Get a Channels
GET {{API_HostAddress}}/f9f733f8-3eeb-4e00-a8b8-996d50fa6f6a
Accept: application/json
Cookie: AccessToken=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6Ik5hZ3kgSXN0dsOhbiIsIm5hbWVpZCI6IjgyOTA1Y2RkLWY2NjEtNDM5MC1iNDAxLTYxNzAzYTE0NjQxNyIsImVtYWlsIjoibmFneUBjcy5jcyIsIlByb3ZpZGVyIjoiIiwibmJmIjoxNzM2MjY5NTUwLCJleHAiOjE3MzYyNjk4NTAsImlhdCI6MTczNjI2OTU1MH0.bc8lLGBBkEvldvvYlubwRYCBNheo2oWKAvPivAOuypCZ3IT6lsElz1KWjhuUa-fEcw0t7NWkC5DY-Y9GOU4fWw

###


#Create Channel
POST {{API_HostAddress}}
Accept: application/json
Content-Type: application/json
Cookie: AccessToken=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IkNzYWJhIEbDtmxkZXNpIiwibmFtZWlkIjoiMjJhMTEwNmQtOThkMy00ZDA5LWExZWYtNTYxZjJlYTljOTJiIiwiZW1haWwiOiJjc2FidXNAZ21haWwuY29tIiwiUHJvdmlkZXIiOiJHaXRIdWIiLCJuYmYiOjE3MzYwMDgwMTQsImV4cCI6MTczNjAwODMxNCwiaWF0IjoxNzM2MDA4MDE0fQ.AX0roWEejgT7p89QLg2b9bXTWy7XmF2VQYi8akkZSTzIdkwTRsnsEzNK8Wt3yRrT4-cmV-q2T-PbvH_5PV-5Bg

{
    "name": "Another  test Channel",
    "workspaceId": "ff77c220-3fcc-448e-b2ce-e25a8c263b4d"
}
###