@API_HostAddress = http://localhost:5000/api/channel


# Get Workspaces Channels
GET {{API_HostAddress}}/list?workspaceId=0eb2a9d5-30bd-425f-a1db-091bc3597647
Accept: application/json
Cookie: AccessToken=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IkNzYWJhIEbDtmxkZXNpIiwibmFtZWlkIjoiMjJhMTEwNmQtOThkMy00ZDA5LWExZWYtNTYxZjJlYTljOTJiIiwiZW1haWwiOiJjc2FidXNAZ21haWwuY29tIiwiUHJvdmlkZXIiOiJHaXRIdWIiLCJuYmYiOjE3Mzc1NDIzODQsImV4cCI6MTczNzU0MjY4NCwiaWF0IjoxNzM3NTQyMzg0fQ.x3edJ1H95HmRfCwtrY0-yERciiDmxhPlhkVW5XPbOk8twY_aThKO8QL7wja94wk4yymlqZhVgx9o6QSLVZi77Q

###

# Get a Channels
GET {{API_HostAddress}}/2c351198-844f-42fa-a5a5-392a83c2a858
Accept: application/json
Cookie: AccessToken=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IkNzYWJhIEbDtmxkZXNpIiwibmFtZWlkIjoiMjJhMTEwNmQtOThkMy00ZDA5LWExZWYtNTYxZjJlYTljOTJiIiwiZW1haWwiOiJjc2FidXNAZ21haWwuY29tIiwiUHJvdmlkZXIiOiJHaXRIdWIiLCJuYmYiOjE3Mzc1NDIzODQsImV4cCI6MTczNzU0MjY4NCwiaWF0IjoxNzM3NTQyMzg0fQ.x3edJ1H95HmRfCwtrY0-yERciiDmxhPlhkVW5XPbOk8twY_aThKO8QL7wja94wk4yymlqZhVgx9o6QSLVZi77Q

###


# Create Channel
POST {{API_HostAddress}}
Accept: application/json
Content-Type: application/json
Cookie: AccessToken=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IkNzYWJhIEbDtmxkZXNpIiwibmFtZWlkIjoiMjJhMTEwNmQtOThkMy00ZDA5LWExZWYtNTYxZjJlYTljOTJiIiwiZW1haWwiOiJjc2FidXNAZ21haWwuY29tIiwiUHJvdmlkZXIiOiJHaXRIdWIiLCJuYmYiOjE3MzY1OTU1NDAsImV4cCI6MTczNjU5NTg0MCwiaWF0IjoxNzM2NTk1NTQwfQ.ldApaV7jYy6VL1A00lNutzCa4O20giwu4PaeOAx_UPSCvzgWLBhUuRct-LmpDrV4ITyK7wmTzUoRUJL7q3AOoQ

{
    "name": "Another  test Channel",
    "workspaceId": "0eb2a9d5-30bd-425f-a1db-091bc3597647"
}
###

# Update Channel
PATCH {{API_HostAddress}}/f4e074e4-c627-496a-b47f-d0f036a651cd
Accept: application/json
Content-Type: application/json
Cookie: AccessToken=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IkNzYWJhIEbDtmxkZXNpIiwibmFtZWlkIjoiMjJhMTEwNmQtOThkMy00ZDA5LWExZWYtNTYxZjJlYTljOTJiIiwiZW1haWwiOiJjc2FidXNAZ21haWwuY29tIiwiUHJvdmlkZXIiOiJHaXRIdWIiLCJuYmYiOjE3MzYzNDQ3NzUsImV4cCI6MTczNjM0NTA3NSwiaWF0IjoxNzM2MzQ0Nzc1fQ.b6K2MtHWo9XEdEElPE66YkjrbpdLBkHtDuOSBO8bdNE7zp1GOMuJeKRSzHUGSL8UenInKmIvvaOwZLnLNPWFKQ

{
    "name": "Renamed Workspace"
}
###

# Delete Channels
DELETE  {{API_HostAddress}}/f4e074e4-c627-496a-b47f-d0f036a651cd
Accept: application/json
Cookie: AccessToken=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IkNzYWJhIEbDtmxkZXNpIiwibmFtZWlkIjoiMjJhMTEwNmQtOThkMy00ZDA5LWExZWYtNTYxZjJlYTljOTJiIiwiZW1haWwiOiJjc2FidXNAZ21haWwuY29tIiwiUHJvdmlkZXIiOiJHaXRIdWIiLCJuYmYiOjE3MzYzNDU3MzksImV4cCI6MTczNjM0NjAzOSwiaWF0IjoxNzM2MzQ1NzM5fQ.N5rpq9S6_O1phxEZEzNkNBWqVPtaeXikxDeF34H0HYaOygct8jvZbrLpNRYyFgeGEky8Z9c5Bai4RlCfybASVA

###