@API_HostAddress = http://localhost:5000/api/member

#Get actual user membership of a workspace
GET {{API_HostAddress}}/ff77c220-3fcc-448e-b2ce-e25a8c263b4d
Accept: application/json
Cookie: AccessToken=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IkNzYWJhIEbDtmxkZXNpIiwibmFtZWlkIjoiMjJhMTEwNmQtOThkMy00ZDA5LWExZWYtNTYxZjJlYTljOTJiIiwiZW1haWwiOiJjc2FidXNAZ21haWwuY29tIiwiUHJvdmlkZXIiOiJHaXRIdWIiLCJuYmYiOjE3MzU5OTQyNzYsImV4cCI6MTczNTk5NDU3NiwiaWF0IjoxNzM1OTk0Mjc2fQ.xZLJKQAv25yN4ira3UG2NkYINbcblZ_K6WNfIXRy1lhDC9YIgKCvEoDrVSFHsQyC-pVHWi7nesQitIMqBZ7wjA

###


#Get member list
GET {{API_HostAddress}}/list/ff77c220-3fcc-448e-b2ce-e25a8c263b4d
Accept: application/json
Cookie: AccessToken=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IkNzYWJhIEbDtmxkZXNpIiwibmFtZWlkIjoiMjJhMTEwNmQtOThkMy00ZDA5LWExZWYtNTYxZjJlYTljOTJiIiwiZW1haWwiOiJjc2FidXNAZ21haWwuY29tIiwiUHJvdmlkZXIiOiJHaXRIdWIiLCJuYmYiOjE3MzU5OTQyNzYsImV4cCI6MTczNTk5NDU3NiwiaWF0IjoxNzM1OTk0Mjc2fQ.xZLJKQAv25yN4ira3UG2NkYINbcblZ_K6WNfIXRy1lhDC9YIgKCvEoDrVSFHsQyC-pVHWi7nesQitIMqBZ7wjA

###
