@API_HostAddress = http://localhost:5000/api/member

#Get actual user membership of a workspace
GET {{API_HostAddress}}/97863121-3bfa-4b06-aefc-5e8d150559ef?userId=22a1106d-98d3-4d09-a1ef-561f2ea9c92b
Accept: application/json
Cookie: AccessToken=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IkNzYWJhIEbDtmxkZXNpIiwibmFtZWlkIjoiMjJhMTEwNmQtOThkMy00ZDA5LWExZWYtNTYxZjJlYTljOTJiIiwiZW1haWwiOiJjc2FidXNAZ21haWwuY29tIiwiUHJvdmlkZXIiOiJHaXRIdWIiLCJuYmYiOjE3MzcxMjk1ODUsImV4cCI6MTczNzEyOTg4NSwiaWF0IjoxNzM3MTI5NTg1fQ.HeVmbh8gz_k-WXI5zXQiaFFS8ulOyN08ybQeSDw3CUv9g4ar8glrMUficOdlX3IDH_a6Nkgdk6_XLlBzCSyjNg

###


#Get member list
GET {{API_HostAddress}}/list/0eb2a9d5-30bd-425f-a1db-091bc3597647
Accept: application/json
Cookie: AccessToken=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IkNzYWJhIEbDtmxkZXNpIiwibmFtZWlkIjoiMjJhMTEwNmQtOThkMy00ZDA5LWExZWYtNTYxZjJlYTljOTJiIiwiZW1haWwiOiJjc2FidXNAZ21haWwuY29tIiwiUHJvdmlkZXIiOiJHaXRIdWIiLCJuYmYiOjE3MzcxMzAyNTMsImV4cCI6MTczNzEzMDU1MywiaWF0IjoxNzM3MTMwMjUzfQ.LfGGi71AGurEWGwx19EK5Sjsxhk3VK7avu8vNnSfrNRp32xOPtJeJ8LTDNBtTOLmlNPcO6xPg3JRcUn_hrI0IQ

###


# Update member role
PATCH {{API_HostAddress}}/0eb2a9d5-30bd-425f-a1db-091bc3597647
Accept: application/json
Content-Type: application/json
Cookie: AccessToken=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6Ik5hZ3kgSXN0dsOhbiIsIm5hbWVpZCI6IjgyOTA1Y2RkLWY2NjEtNDM5MC1iNDAxLTYxNzAzYTE0NjQxNyIsImVtYWlsIjoibmFneUBjcy5jcyIsIlByb3ZpZGVyIjoiIiwibmJmIjoxNzM3MTMwNTA3LCJleHAiOjE3MzcxMzA4MDcsImlhdCI6MTczNzEzMDUwN30.YUWuTLU0nk08Rf-RgPuocm6hdaTdFdCpZ6L4y_M4RldUbLSSqmfPO8r0I_4fTum0Zl3Opt_swdOuLf2JTZfp6w

{
    "userId": "82905cdd-f661-4390-b401-61703a146417",
    "role": "member"
}
###
