@API_HostAddress = http://localhost:5000/api/member

#Get actual user membership of a workspace
GET {{API_HostAddress}}/97863121-3bfa-4b06-aefc-5e8d150559ef?userId=22a1106d-98d3-4d09-a1ef-561f2ea9c92b
Accept: application/json
Cookie: AccessToken=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IkbDtmxkZXNpIENzYWJhIiwibmFtZWlkIjoiZGMzYzIyOTItMWEzZi00ZmMwLWI4ZjYtYzRkOTNiZTM0MWI4IiwiZW1haWwiOiJjc0Bjcy5jcyIsIlByb3ZpZGVyIjoiIiwibmJmIjoxNzM3MTIxMjk1LCJleHAiOjE3MzcxMjE1OTUsImlhdCI6MTczNzEyMTI5NX0.vLddwAA3G1fLzFsdf3KV0HWtlRuGymth4An25CQ4D9xBpjV3bSG-XJ1fXMrTbpGjPtr2D7n0g723qcN6uBOx_w

###


#Get member list
GET {{API_HostAddress}}/list/97863121-3bfa-4b06-aefc-5e8d150559ef
Accept: application/json
Cookie: AccessToken=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IkbDtmxkZXNpIENzYWJhIiwibmFtZWlkIjoiZGMzYzIyOTItMWEzZi00ZmMwLWI4ZjYtYzRkOTNiZTM0MWI4IiwiZW1haWwiOiJjc0Bjcy5jcyIsIlByb3ZpZGVyIjoiIiwibmJmIjoxNzM3MTIxMjk1LCJleHAiOjE3MzcxMjE1OTUsImlhdCI6MTczNzEyMTI5NX0.vLddwAA3G1fLzFsdf3KV0HWtlRuGymth4An25CQ4D9xBpjV3bSG-XJ1fXMrTbpGjPtr2D7n0g723qcN6uBOx_w

###
