@API_HostAddress = http://localhost:5000/api/message

# Create Message
POST {{API_HostAddress}}
Accept: application/json
Content-Type: application/json
Cookie: AccessToken=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IkNzYWJhIEbDtmxkZXNpIiwibmFtZWlkIjoiMjJhMTEwNmQtOThkMy00ZDA5LWExZWYtNTYxZjJlYTljOTJiIiwiZW1haWwiOiJjc2FidXNAZ21haWwuY29tIiwiUHJvdmlkZXIiOiJHaXRIdWIiLCJuYmYiOjE3MzY2OTc4ODcsImV4cCI6MTczNjY5ODE4NywiaWF0IjoxNzM2Njk3ODg3fQ.rxENKYIDFI9UTCt1ap-3s59RsF8rDgsVECCqanJfKd7tmCw7HqC86iJACFKyZSqG0adwJEtValr-4ZvGO2JmnQ

{
  "channelId": "f7614ad3-88c3-4b01-8fa4-b0ffa674c756",
  "workspaceId": "886eb85e-445e-495a-8c7f-6c0c65f22f68",
  "body": "Message"
}
###


#Get Message List by channel
GET {{API_HostAddress}}?channelid=2c351198-844f-42fa-a5a5-392a83c2a858
Accept: application/json
Content-Type: application/json
Cookie: AccessToken=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IkNzYWJhIEbDtmxkZXNpIiwibmFtZWlkIjoiMjJhMTEwNmQtOThkMy00ZDA5LWExZWYtNTYxZjJlYTljOTJiIiwiZW1haWwiOiJjc2FidXNAZ21haWwuY29tIiwiUHJvdmlkZXIiOiJHaXRIdWIiLCJuYmYiOjE3MzcyODg2OTQsImV4cCI6MTczNzI4ODk5NCwiaWF0IjoxNzM3Mjg4Njk0fQ.CuFtkqj27OY1UeF0gALutZKXykeewwdv160njppBofiR9g-alnbtBljLJqV_sHL8tJ987qeREmIRjMyzpTwLkQ

###

#Get a Message
GET {{API_HostAddress}}/e71fa26f-7121-4e2d-9819-315d58de74c0
Accept: application/json
Content-Type: application/json
Cookie: AccessToken=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IkNzYWJhIEbDtmxkZXNpIiwibmFtZWlkIjoiMjJhMTEwNmQtOThkMy00ZDA5LWExZWYtNTYxZjJlYTljOTJiIiwiZW1haWwiOiJjc2FidXNAZ21haWwuY29tIiwiUHJvdmlkZXIiOiJHaXRIdWIiLCJuYmYiOjE3MzcyMzk3OTgsImV4cCI6MTczNzI0MDA5OCwiaWF0IjoxNzM3MjM5Nzk4fQ.4yARBACeAmJSb_ogrTamqSoTpe8X2rLAzkJxy3GB-BL15uTtofQqYJ7x08urNmRYGPtRDi0JNWgW6tcP5NrSlg

###



# Update Message
PATCH {{API_HostAddress}}/00b6d74f-18ef-41a5-8fb3-6c09ec529291
Accept: application/json
Content-Type: application/json
Cookie: AccessToken=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IkbDtmxkZXNpIENzYWJhIiwibmFtZWlkIjoiZGMzYzIyOTItMWEzZi00ZmMwLWI4ZjYtYzRkOTNiZTM0MWI4IiwiZW1haWwiOiJjc0Bjcy5jcyIsIlByb3ZpZGVyIjoiIiwibmJmIjoxNzM2ODg1Mzg0LCJleHAiOjE3MzY4ODU2ODQsImlhdCI6MTczNjg4NTM4NH0.qZy0OTheWB2dhI8BPv0lPGspNL9MWMuQiAAooY2SLDGJsjtX2Cz9K0wIpI2enD9aLWyFYoPUUUdzQYv9QFNrnQ

{
  "body": "{\"ops\":[{\"insert\":\"mi\\n\"}]}"
}
###

# Delete Message
DELETE {{API_HostAddress}}/34d467c4-912e-48c6-abdb-600c561e8ed8
Accept: application/json
Content-Type: application/json
Cookie: AccessToken=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IkbDtmxkZXNpIENzYWJhIiwibmFtZWlkIjoiZGMzYzIyOTItMWEzZi00ZmMwLWI4ZjYtYzRkOTNiZTM0MWI4IiwiZW1haWwiOiJjc0Bjcy5jcyIsIlByb3ZpZGVyIjoiIiwibmJmIjoxNzM2OTQwNDY4LCJleHAiOjE3MzY5NDA3NjgsImlhdCI6MTczNjk0MDQ2OH0.I7WlndpScYrvbDzozn6JqdAzvhlxf4gyPRJQwKG5CCX_xOnC_YjvGZS1pM7gSnjwHABXsETl__rgZ4zqL4JtKw

###

# Toggle Reaction
PATCH {{API_HostAddress}}/f189a54a-1af0-4015-bf6e-ebffa1033383/reaction
Accept: application/json
Content-Type: application/json
Cookie: AccessToken=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IkNzYWJhIEbDtmxkZXNpIiwibmFtZWlkIjoiMjJhMTEwNmQtOThkMy00ZDA5LWExZWYtNTYxZjJlYTljOTJiIiwiZW1haWwiOiJjc2FidXNAZ21haWwuY29tIiwiUHJvdmlkZXIiOiJHaXRIdWIiLCJuYmYiOjE3MzY5NTQ1OTUsImV4cCI6MTczNjk1NDg5NSwiaWF0IjoxNzM2OTU0NTk1fQ.VI746hVxWzSq2Auufx6wN0ORxQwydeB81yIG46KtYrclnlnY7L1Bm4sMqVdrco_3_asaXQK6xXFpCGjhW16Ppg

{
  "value": "S"
}
###