@API_HostAddress = http://localhost:5000/api/workspace

# Get user Workspaces
GET {{API_HostAddress}}
Accept: application/json
Cookie: AccessToken=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IkNzYWJhIEbDtmxkZXNpIiwibmFtZWlkIjoiMjJhMTEwNmQtOThkMy00ZDA5LWExZWYtNTYxZjJlYTljOTJiIiwiZW1haWwiOiJjc2FidXNAZ21haWwuY29tIiwiUHJvdmlkZXIiOiJHaXRIdWIiLCJuYmYiOjE3MzU4Mjc2MjcsImV4cCI6MTczNTgyNzkyNywiaWF0IjoxNzM1ODI3NjI3fQ.8JPTrwkcnSwWz-93bZ1Ftu6V6qRhjQ_9Gckb80g9helSgmgeyFxiqZLtacPRQSCj_uC5FYcr1xtHhicGTAknag

###

# Create Workspace
POST {{API_HostAddress}}
Accept: application/json
Content-Type: application/json
Cookie: AccessToken=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IkNzYWJhIEbDtmxkZXNpIiwibmFtZWlkIjoiMjJhMTEwNmQtOThkMy00ZDA5LWExZWYtNTYxZjJlYTljOTJiIiwiZW1haWwiOiJjc2FidXNAZ21haWwuY29tIiwiUHJvdmlkZXIiOiJHaXRIdWIiLCJuYmYiOjE3MzU4Mjc2MjcsImV4cCI6MTczNTgyNzkyNywiaWF0IjoxNzM1ODI3NjI3fQ.8JPTrwkcnSwWz-93bZ1Ftu6V6qRhjQ_9Gckb80g9helSgmgeyFxiqZLtacPRQSCj_uC5FYcr1xtHhicGTAknag

{
    "name": "Test workspace"
}
###