@API_HostAddress = http://localhost:5000/api/workspace

# List user Workspaces
GET {{API_HostAddress}}
Accept: application/json
Cookie: AccessToken=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IkNzYWJhIEbDtmxkZXNpIiwibmFtZWlkIjoiMjJhMTEwNmQtOThkMy00ZDA5LWExZWYtNTYxZjJlYTljOTJiIiwiZW1haWwiOiJjc2FidXNAZ21haWwuY29tIiwiUHJvdmlkZXIiOiJHaXRIdWIiLCJuYmYiOjE3MzYwMjEzMjAsImV4cCI6MTczNjAyMTYyMCwiaWF0IjoxNzM2MDIxMzIwfQ.2arbP6gX2Mz_u0_iuwhLiTnGktsRm_KfGaRm1R6TNJEa0QHIXIj-qwMjLeQcfp9Lho8d_4uDCjbfk0rXbkhdPg

###

# Get a Workspaces
GET {{API_HostAddress}}/ff77c220-3fcc-448e-b2ce-e25a8c263b4d
Accept: application/json
Cookie: AccessToken=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IkNzYWJhIEbDtmxkZXNpIiwibmFtZWlkIjoiMjJhMTEwNmQtOThkMy00ZDA5LWExZWYtNTYxZjJlYTljOTJiIiwiZW1haWwiOiJjc2FidXNAZ21haWwuY29tIiwiUHJvdmlkZXIiOiJHaXRIdWIiLCJuYmYiOjE3MzYwMTk0NzUsImV4cCI6MTczNjAxOTc3NSwiaWF0IjoxNzM2MDE5NDc1fQ.Q8KYhhgSU6-H3F586uhq6x9hxsohXWMQSTaguRcW0rBtBjohpipBPNgXgoGNag5kLoTdvqLc4fjG9nzWWBRkjA

###


# Create Workspace
POST {{API_HostAddress}}
Accept: application/json
Content-Type: application/json
Cookie: AccessToken=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IkNzYWJhIEbDtmxkZXNpIiwibmFtZWlkIjoiMjJhMTEwNmQtOThkMy00ZDA5LWExZWYtNTYxZjJlYTljOTJiIiwiZW1haWwiOiJjc2FidXNAZ21haWwuY29tIiwiUHJvdmlkZXIiOiJHaXRIdWIiLCJuYmYiOjE3MzU4MzE3MTQsImV4cCI6MTczNTgzMjAxNCwiaWF0IjoxNzM1ODMxNzE0fQ.0p8_VnKge4T1xd-U1jm7PiE1N-T-4DxfMfwvZacgApVsyppQ8sTBbBqy_pCxPERC6143cGY5dw1LsoM08HmvYw

{
    "name": "Work"
}
###


# Generate new join code for a workspace
POST {{API_HostAddress}}/newjoincode/ff77c220-3fcc-448e-b2ce-e25a8c263b4d
Accept: application/json
Cookie: AccessToken=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IkNzYWJhIEbDtmxkZXNpIiwibmFtZWlkIjoiMjJhMTEwNmQtOThkMy00ZDA5LWExZWYtNTYxZjJlYTljOTJiIiwiZW1haWwiOiJjc2FidXNAZ21haWwuY29tIiwiUHJvdmlkZXIiOiJHaXRIdWIiLCJuYmYiOjE3MzYwMTc1MDMsImV4cCI6MTczNjAxNzgwMywiaWF0IjoxNzM2MDE3NTAzfQ.CTBAUQT9BzGepTwbefr-70hNNXT5AwsdmNKee3OB_m4zmIBGmQFtufw8R1EILqgoKfs83DK5B2LH3MZRZcr-aw

###


# Rename workspace
PATCH {{API_HostAddress}}/ff77c220-3fcc-448e-b2ce-e25a8c263b4d
Accept: application/json
Content-Type: application/json
Cookie: AccessToken=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IkNzYWJhIEbDtmxkZXNpIiwibmFtZWlkIjoiMjJhMTEwNmQtOThkMy00ZDA5LWExZWYtNTYxZjJlYTljOTJiIiwiZW1haWwiOiJjc2FidXNAZ21haWwuY29tIiwiUHJvdmlkZXIiOiJHaXRIdWIiLCJuYmYiOjE3MzYwMTk0NzUsImV4cCI6MTczNjAxOTc3NSwiaWF0IjoxNzM2MDE5NDc1fQ.Q8KYhhgSU6-H3F586uhq6x9hxsohXWMQSTaguRcW0rBtBjohpipBPNgXgoGNag5kLoTdvqLc4fjG9nzWWBRkjA

{
    "id": "assd",
    "name": "Home renamed"
}
###


# Delete workspace
DELETE {{API_HostAddress}}/a4885545-2158-400c-8833-95f7a6c4ce36
Accept: application/json
Content-Type: application/json
Cookie: AccessToken=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IkNzYWJhIEbDtmxkZXNpIiwibmFtZWlkIjoiMjJhMTEwNmQtOThkMy00ZDA5LWExZWYtNTYxZjJlYTljOTJiIiwiZW1haWwiOiJjc2FidXNAZ21haWwuY29tIiwiUHJvdmlkZXIiOiJHaXRIdWIiLCJuYmYiOjE3MzYwMjEzMjAsImV4cCI6MTczNjAyMTYyMCwiaWF0IjoxNzM2MDIxMzIwfQ.2arbP6gX2Mz_u0_iuwhLiTnGktsRm_KfGaRm1R6TNJEa0QHIXIj-qwMjLeQcfp9Lho8d_4uDCjbfk0rXbkhdPg

###