@API_HostAddress = http://localhost:5000/api/workspace

# Get user Workspaces
GET {{API_HostAddress}}
Accept: application/json
Cookie: AccessToken=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IkNzYWJhIEbDtmxkZXNpIiwibmFtZWlkIjoiMjJhMTEwNmQtOThkMy00ZDA5LWExZWYtNTYxZjJlYTljOTJiIiwiZW1haWwiOiJjc2FidXNAZ21haWwuY29tIiwiUHJvdmlkZXIiOiJHaXRIdWIiLCJuYmYiOjE3MzU4MzE3MTQsImV4cCI6MTczNTgzMjAxNCwiaWF0IjoxNzM1ODMxNzE0fQ.0p8_VnKge4T1xd-U1jm7PiE1N-T-4DxfMfwvZacgApVsyppQ8sTBbBqy_pCxPERC6143cGY5dw1LsoM08HmvYw

###

# Create Workspace
POST {{API_HostAddress}}
Accept: application/json
Content-Type: application/json
Cookie: AccessToken=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IkNzYWJhIEbDtmxkZXNpIiwibmFtZWlkIjoiMjJhMTEwNmQtOThkMy00ZDA5LWExZWYtNTYxZjJlYTljOTJiIiwiZW1haWwiOiJjc2FidXNAZ21haWwuY29tIiwiUHJvdmlkZXIiOiJHaXRIdWIiLCJuYmYiOjE3MzU4MzE3MTQsImV4cCI6MTczNTgzMjAxNCwiaWF0IjoxNzM1ODMxNzE0fQ.0p8_VnKge4T1xd-U1jm7PiE1N-T-4DxfMfwvZacgApVsyppQ8sTBbBqy_pCxPERC6143cGY5dw1LsoM08HmvYw

{
    "name": "Work"
}
###